global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'authorization-server'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['authorization:8080'] # Update the port and host as necessary
  - job_name: 'income-expense'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['incomeexpense:8082'] # Update the port and host as necessary
